name       : log4perl
version    : 1.47
release    : 1
source     :
    - http://www.cpan.org/authors/id/M/MS/MSCHILLI/Log-Log4perl-1.47.tar.gz : 9001dded011226538b9a50c7856815bb0dba72a1e6218fdcaba56f651356b96f
license    : GPL-2.0
component  : programming.perl
summary    : Log4j implementation for Perl
description: |
    Log4j implementation for Perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
