name       : log4perl
version    : '1.49'
release    : 10
source     :
    - https://www.cpan.org/authors/id/M/MS/MSCHILLI/Log-Log4perl-1.49.tar.gz : b739187f519146cb6bebcfc427c64b1f4138b35c5f4c96f46a21ed4a43872e16
license    : GPL-2.0-or-later
component  : programming.perl
summary    : Log4j implementation for Perl
description: |
    Log4j implementation for Perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
